[Fix][Android] Fix the andoidx.appcompat that is incompatibility caused compile error
1.error: 'AAPT: error: resource android:attr/lStar' not found when building apk in release mode
2.causes: androidx.appcompat incompatibility

Signed-off-by: zhuyangyang <yangyang.zhu@pplingo.com>